media:
  input: src/assets/images
  output: ./assets
content:
  - name: posts
    type: collection
    path: src/data/blog
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: text
      - name: draft
        label: Is draft?
        type: select
        options:
          values: [true, false]
      - name: featured
        label: Is featured?
        type: select
        options:
          values: [true, false]
      - name: pubDatetime
        label: Published Datetime
        type: date
        options: 
          time: true
          format: "yyyy-MM-dd'T'HH:mm:ss'Z'"
      - name: heroImage
        label: Hero Image
        type: image
      - name: body
        label: Body
        type: rich-text
    view:
      fields: [title, description, pubDatetime, heroImage]